apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-pods   # MUST match pod labels
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 5000  #MUST match container port
