apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-express   
  labels:
    app: mongodb-client     
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-expr-pod
  template:
    metadata:
      labels:
        app: mongodb-expr-pod
    spec:
      containers:
      - name: mongodb-expr-container 
        image: mongo-express:latest
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-user
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          #value: mongodb-service
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: database_url
        - name: ME_CONFIG_BASICAUTH_USERNAME
          value: admin
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          value: edwin